[package]
name = "rust-basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[example]]
name = "data_types"
path = "./src/basics/data_types.rs"

[[example]]
name = "variables"
path = "./src/basics/variables.rs"

[dependencies]
